### ISSUE TITLE
Adding more functionalities

### ISSUE THREAD

**Issue by rehabaam** [kyo504/react-native-audio-streaming-player#2]
Hi Hunkyo,

I am using this package for one mobile app I am making and I am wondering if you are going to add more functionalities to this package like getDuration, read from local files for network exceptions, skipping 10sec, etc.

I already updated RNAudioPlayer file to read local files with specific key sent to it but I think it would be better if this package gets more updates as it is excellent one compared to the other RN libs/packages.

**Comment by kyo504** [comment]
@rehabaam Thanks for the functionalities. If you open a PR, I'll take a look at it.

**Comment by rehabaam** [comment]
@kyo504 sure, I will do that soon!
